### ISSUE TITLE
Look for LRU Caching Algorithm

### ISSUE THREAD

**Issue by warnke** [jusjusjus/justcache#1]
What happens if you put more than 1024 in there? Check out LRU. You can increase the coolness a lot. Also, looking forward to seeing you next weekend. A lot.

**Comment by jusjusjus** [comment]
You run out of cache, that's what happens. #fastcache_is_good_library

**Comment by warnke** [comment]
LRYouDaemel

On Thu, Aug 31, 2017 at 9:51 AM, Justus Schwabedal <notifications@github.com

**Comment by jusjusjus** [comment]
Happy now?
